2019-12-11 13:45:01,216 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():54                | Arguments:
{'callbacks_args': [],
 'dataset_args': {'name': <SupportedDataset.MNIST_Enum: {'dataloader': <class 'dataset.MNIST.MNIST'>, 'image_size': (32, 32), 'channels': 1, 'training_size': 60000, 'labels_count': 10}>,
                  'training_subset_percentage': 1.0},
 'loss_args': {'name': 'torch.nn.CrossEntropyLoss'},
 'mode': 'classification',
 'model_args': {'model_arch_name': 'models.classification.ConvNetSimple.ConvNetSimple',
                'model_constructor_args': {'input_size': (32, 32),
                                           'number_of_classes': 10,
                                           'number_of_input_channels': 1},
                'model_weights_path': None},
 'nb_epochs': 50,
 'optimizer_args': {'lr': 0.001, 'name': 'torch.optim.Adam'},
 'outdir': './logs/',
 'random_seed': 42,
 'train_data_args': {'batch_size': 64, 'shuffle': True, 'to_train': True},
 'val_data_args': {'batch_size': 256,
                   'shuffle': False,
                   'validate_step_size': 1}}
2019-12-11 13:45:01,216 |     MainProcess | MainThread | INFO  | tensorboard_writer.py::initialize_tensorboard():64 | Initializing Tensorboard Writer in ./logs/2019-12-11T13:45:01.171945_model_ConvNetSimple_dataset_MNIST_subset_1.0_bs_64_name_Adam_lr_0.001
2019-12-11 13:45:01,217 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():60                | Using Random Seed value as: 42
2019-12-11 13:45:01,227 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():67                | Using device - cuda:0
2019-12-11 13:45:03,982 |     MainProcess | MainThread | INFO  | MNIST.py::__init__():32                            | Mean and Std used: (0.5,), (0.5,)
2019-12-11 13:45:11,594 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.3016983016983 %%
2019-12-11 13:45:17,921 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.56809856809856 %%
2019-12-11 13:45:24,278 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.53479853479854 %%
2019-12-11 13:45:30,610 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.41824841824842 %%
2019-12-11 13:45:37,301 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.75124875124875 %%
2019-12-11 13:45:44,151 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.78454878454879 %%
2019-12-11 13:45:50,920 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.75124875124875 %%
2019-12-11 13:45:57,710 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.9010989010989 %%
2019-12-11 13:46:04,502 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.08424908424908 %%
2019-12-11 13:46:11,268 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.98434898434898 %%
2019-12-11 13:46:18,036 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.03429903429904 %%
2019-12-11 13:46:24,709 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.03429903429904 %%
2019-12-11 13:46:31,549 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.08424908424908 %%
2019-12-11 13:46:38,351 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.11754911754912 %%
2019-12-11 13:46:45,171 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.85114885114885 %%
2019-12-11 13:46:51,953 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.03429903429904 %%
2019-12-11 13:46:58,758 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.15084915084915 %%
2019-12-11 13:47:05,482 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.1008991008991 %%
2019-12-11 13:47:12,168 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.28404928404929 %%
2019-12-11 13:47:18,874 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.13419913419914 %%
2019-12-11 13:47:25,653 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.15084915084915 %%
2019-12-11 13:47:32,410 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.2007992007992 %%
2019-12-11 13:47:40,188 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.000999000999 %%
2019-12-11 13:47:47,425 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.23409923409923 %%
2019-12-11 13:47:55,411 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.05094905094906 %%
2019-12-11 13:48:04,255 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.13419913419914 %%
2019-12-11 13:48:12,412 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.01764901764902 %%
2019-12-11 13:48:21,818 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.16749916749917 %%
2019-12-11 13:48:30,811 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.18414918414918 %%
2019-12-11 13:48:38,652 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.21744921744921 %%
2019-12-11 13:48:45,497 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.16749916749917 %%
2019-12-11 13:48:52,176 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.16749916749917 %%
2019-12-11 13:48:59,012 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.28404928404929 %%
2019-12-11 13:49:05,582 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.01764901764902 %%
2019-12-11 13:49:12,254 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.01764901764902 %%
2019-12-11 13:49:19,004 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.03429903429904 %%
2019-12-11 13:49:25,698 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.15084915084915 %%
2019-12-11 13:49:32,361 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.1008991008991 %%
2019-12-11 13:49:39,099 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.15084915084915 %%
2019-12-11 13:49:45,837 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.28404928404929 %%
2019-12-11 13:49:52,791 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.03429903429904 %%
2019-12-11 13:50:00,221 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.1008991008991 %%
2019-12-11 13:50:07,252 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.000999000999 %%
2019-12-11 13:50:14,289 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.06759906759906 %%
2019-12-11 13:50:21,238 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.08424908424908 %%
2019-12-11 13:50:28,280 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.21744921744921 %%
2019-12-11 13:50:35,289 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 98.98434898434898 %%
2019-12-11 13:50:42,289 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.25074925074925 %%
2019-12-11 13:50:49,284 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.05094905094906 %%
2019-12-11 13:50:56,328 |     MainProcess | MainThread | INFO  | train_classifier.py::objective():166               | Accuracy of the network on the 6006 validation images: 99.26739926739927 %%
2019-12-11 13:50:56,328 |     MainProcess | MainThread | DEBUG | train_classifier.py::main():272                    | Exception caught from objective function
Traceback (most recent call last):
  File "/home/sk/workspace/MLMI/train_classifier.py", line 270, in main
    objective(arguments)
  File "/home/sk/workspace/MLMI/train_classifier.py", line 180, in objective
    run_callbacks(callbacks, model=model, mode=CallbackMode.ON_TRAIN_END)
TypeError: run_callbacks() missing 1 required positional argument: 'optimizer'
